### ISSUE TITLE
Refactor acquisition scheme to take empty deltas for clinical data

### ISSUE THREAD

**Issue by sitek** [AthenaEPI/dmipy#33]
I'm attempting to set up an acquisition scheme for CSD for some data from a collaborator, and I'm having trouble finding little delta and big Delta, despite having the DICOM header. Where should I start looking for these values?

In trying to set up my analysis, one reference has been`tutorial_setting_up_acquisition_scheme.ipynb`. That notebook sets up the acquisition scheme for HCP data and says that
`the delta and Delta times we know from the HCP documentation in seconds`.
However, I'm also unable to find those values in the HCP docs (for instance, under "Diffusion Session Scan Protocol" in https://humanconnectome.org/storage/app/media/documentation/s1200/HCP_S1200_Release_Appendix_I.pdf.

**Comment by rutgerfick** [comment]
Concerning the WU-Minn HCP diffusion times, I don't know why they're not included in the scanning protocol, but you can find them their accompanying paper:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3720790/

**Comment by sitek** [comment]
Thank you @rutgerfick! I'll use the HCP times without restricted models for now.

**Comment by rutgerfick** [comment]
Reopening issue to remind making adjustments to the acquisition schemes take take empty deltas and only throw an error with models are used that require deltas.

**Comment by rutgerfick** [comment]
Hi @sitek , you should now be able to use the acquisition schemes directly without having to put in fake delta/Delta values. Just load the latest version and the tutorial notebook is updated.
