### ISSUE TITLE
does noddi need delta [ms]  and |Delta[ms]?

### ISSUE THREAD

**Issue by foxet** [AthenaEPI/dmipy#59]
delta [ms] |Delta[ms]

**Comment by foxet** [comment]
does noddi need delta [ms] and |Delta[ms]?

**Comment by rutgerfick** [comment]
Nope.

delta/Delta are only needed when you include a CompartmentModel like a cylinder, sphere, or restricted zeppelin (C2-4, S2-4, G3).

You can just set the acquisition scheme using only b-values and gradient directions as in the [tutorial](https://nbviewer.jupyter.org/github/AthenaEPI/dmipy/blob/master/examples/tutorial_setting_up_acquisition_scheme.ipynb)

**Comment by foxet** [comment]
rutgerfick c thankyou
