### ISSUE TITLE
A little confuse about the explaination for noddi parameter's maps

### ISSUE THREAD

**Issue by foxet** [AthenaEPI/dmipy#62]
The explanation for parameter's maps followed is from example_noddi_watson.ipynb
_

> "Above we see the familiar maps. Remember that partial_volume_0/1/2 represent fractions of models in the order they were given to the MultiCompartmentMicrostructureModel object. In this case, 0 represents the fraction of Ball (CSF), and the 1 represents the Stick (intra-axonal) and 2 represents the zeppelin (extra-axonal).
> 
> In the bottom-right ODI map you can see that the concentration is highest in the corpus callosum and in coherent white matter bundles. Finally, the  𝜆∥  and  𝜆iso  maps are fixed to the values we gave them."

_
![图片](https://user-images.githubusercontent.com/1968438/59079922-a4495300-8918-11e9-94fc-70ad76834f18.png)

I think the **partial_volume_0** is from G1ball, represents  fraction of CSF

I have two questions:
**1.  what's the parameters for partial_volume_1 and partial_volume_2   in the explaination 

Does it refers to  'partial_volume_1' and  'SD1WatsonDistributed_1_partial_volume_0'?
or refers to:
'SD1WatsonDistributed_1_partial_volume_0' and  'SD1WatsonDistributed_1_SD1Watson_1_mu'

2. Is the map for Stick (intra-axonal) parameter equal to NDI (neurite density index ) map?**

Here's the watson parameters:
NODDI_mod.parameter_names

**['G1Ball_1_lambda_iso',        
 'SD1WatsonDistributed_1_SD1Watson_1_mu',
 'SD1WatsonDistributed_1_partial_volume_0',
 'SD1WatsonDistributed_1_SD1Watson_1_odi',
 'partial_volume_0',
 'partial_volume_1']**

It would be appreciated that if you could help, : )

**Comment by rutgerfick** [comment]
Hey!

I updated the example where i explicitly compute the stick and zeppelin maps from the parameters: https://github.com/AthenaEPI/dmipy/blob/master/examples/example_noddi_watson.ipynb

Answers to your question
1. partial_volume_0 is for the ball, and partial_volume_1 is for the Watson Bundle. SD1WatsonDistributed_1_partial_volume_0 is for the Stick INSIDE the watson bundle, and (1-SD1WatsonDistributed_1_partial_volume_0) is for the zeppelin (so the complement). To the get signal contribution of the Stick and Zeppelin to the total signal, you have to multiply them by the fraction of the watson bundle (partial_volume_1).

2. So, the stick in the model represents the intra-axonal/neurite fraction, and the zeppelin the extra-axonal/neurite fraction. The total neurite / white matter fraction is thus the sum of these two, which is just partial_volume_1. So, it depends what you want, and what you define NDI to be :-)

**Comment by foxet** [comment]
very clear now, thankyou rutgerfick
