### ISSUE TITLE
about parameters for verdict model

### ISSUE THREAD

**Issue by foxet** [AthenaEPI/dmipy#64]
![图片](https://user-images.githubusercontent.com/1968438/59393816-b95a3200-8daf-11e9-8c9e-10afd7d5abca.png)

['S4SphereGaussianPhaseApproximation_1_diameter',
 'G1Ball_1_lambda_iso',
 'C1Stick_1_mu',
 'C1Stick_1_lambda_par',
 'partial_volume_0',
 'partial_volume_1',
 'partial_volume_2']

**Does the partial_volume_0/1/2 represent tumor, extra-cell, and vascular respectively?**

**Comment by rutgerfick** [comment]
`verdict_mod = MultiCompartmentModel(models=[sphere, ball, stick])`

The volume fractions are ordered according to the ordering of the input models.

So, according to the way the model in the example in the set up, you're completely correct :-)
