### ISSUE TITLE
Clipping Signal Decay Metric above 10 to 10

### ISSUE THREAD

**Issue by rutgerfick** [AthenaEPI/dmipy#68]
Following discussion in #67 and suggestion by @thijsdhollander.

Option to clip SDM above certain number to avoid noisy CSF response functions.

**Comment by thijsdhollander** [comment]
Yep, as I've explained a bit [here](https://github.com/AthenaEPI/dmipy/pull/67#issuecomment-510783172), this is a safe heuristic, intended to avoid the extremely unlikely (unless in case of extremely challenging SNR) case of an extreme SDM outlier, which might cause trouble down the track in the algorithm.  But as also mentioned, there's no reason to lose the voxel itself: with a very high (beyond the clipping threshold) SDM value, it's certainly highly indicative of a genuine CSF voxel, even if the diffusivity might not be spot-on.  That's ok, as the actual point of the algorithm is to get the responses from the data itself, without too many physical assumptions beyond general "relative" properties and differences between/among the 3 tissue types.  If that weren't the case, you'd define the responses by a biophysical model anyway (e.g. like NODDI and others do).
