### ISSUE TITLE
median_otsu misused in three_tissue_response_dhollander16

### ISSUE THREAD

**Issue by matteofrigo** [AthenaEPI/dmipy#76]
The `median_otsu` method from `dipy` takes as input the variable `vol_idx` which must be an iterable.
In the `three_tissue_response_dhollander16` function this parameter is [passed as a scalar](https://github.com/AthenaEPI/dmipy/blob/980f43968b724aa16040b406f2f5e4914840f400/dmipy/tissue_response/three_tissue_response.py#L91).

I'll fix it and push a PR, but we should be aware of the fact that this could be happening somewhere else. It may be due to the recent dipy update (v1.0) but again, I'm not sure and this must be checked.

**Comment by matteofrigo** [comment]
The [old](https://github.com/nipy/dipy/blob/02ea177646ef5cb0abf812f31ba3e815abac8565/dipy/segment/mask.py#L122) syntax is 

```
median_otsu(input_volume, median_radius=4, numpass=4,
autocrop=False, vol_idx=None, dilate=None):
```

The [new](https://github.com/nipy/dipy/blob/746d3332f294ad014e17992d5a92eb428aa16105/dipy/segment/mask.py#L122) one is

```
median_otsu(input_volume, vol_idx=None, median_radius=4, numpass=4,
autocrop=False, dilate=None):
```

**Comment by heejong-kim** [comment]
Hi, "b0_mask, mask = median_otsu(data, 2, 1)" still makes the problem of iteration. If you wanted the voxel indices to be [2,1], you may want to update this part as well.

**Comment by rutgerfick** [comment]
Hi @heejong-kim, following your comment I just updated the usage of the median_otsu function as suggested. Things should work now as expected!
