### ISSUE TITLE
probably unwanted print spherical mean

### ISSUE THREAD

**Issue by matteofrigo** [AthenaEPI/dmipy#79]
The `dmipy.utils.estimate_spherical_mean_shell` function [prints the value](https://github.com/AthenaEPI/dmipy/blob/5f03f42875abe58c2b46994309354fd790b9cdab/dmipy/utils/spherical_mean.py#L87) of the spherical mean every time it is called. This information may not be interesting in every single case.

I propose to eliminate this print.

**Comment by rutgerfick** [comment]
Completely accepted, must have been a leftover of some test.
